# This file is auto-generated by the Perl DateTime Suite time zone
# code generator (0.07) This code generator comes with the
# DateTime::TimeZone module distribution in the tools/ directory

#
# Generated from /tmp/QHGEm1kC2X/asia.  Olson data version 2010e
#
# Do not edit this file directly.
#
package DateTime::TimeZone::Asia::Dhaka;

use strict;

use Class::Singleton;
use DateTime::TimeZone;
use DateTime::TimeZone::OlsonDB;

@DateTime::TimeZone::Asia::Dhaka::ISA = ( 'Class::Singleton', 'DateTime::TimeZone' );

my $spans =
[
    [
DateTime::TimeZone::NEG_INFINITY,
59611139900,
DateTime::TimeZone::NEG_INFINITY,
59611161600,
21700,
0,
'LMT'
    ],
    [
59611139900,
61244100400,
59611161100,
61244121600,
21200,
0,
'HMT'
    ],
    [
61244100400,
61263624600,
61244123800,
61263648000,
23400,
0,
'BURT'
    ],
    [
61263624600,
61273045800,
61263644400,
61273065600,
19800,
0,
'IST'
    ],
    [
61273045800,
61559544600,
61273069200,
61559568000,
23400,
0,
'BURT'
    ],
    [
61559544600,
62174455200,
61559566200,
62174476800,
21600,
0,
'DACT'
    ],
    [
62174455200,
63366429600,
62174476800,
63366451200,
21600,
0,
'BDT'
    ],
    [
63366429600,
63381114000,
63366451200,
63381135600,
21600,
0,
'BDT'
    ],
    [
63381114000,
63397961940,
63381139200,
63397987140,
25200,
1,
'BDST'
    ],
    [
63397961940,
63405737940,
63397983540,
63405759540,
21600,
0,
'BDT'
    ],
    [
63405737940,
63424227540,
63405763140,
63424252740,
25200,
1,
'BDST'
    ],
    [
63424227540,
63437273940,
63424249140,
63437295540,
21600,
0,
'BDT'
    ],
    [
63437273940,
63455763540,
63437299140,
63455788740,
25200,
1,
'BDST'
    ],
    [
63455763540,
63468896340,
63455785140,
63468917940,
21600,
0,
'BDT'
    ],
    [
63468896340,
63487385940,
63468921540,
63487411140,
25200,
1,
'BDST'
    ],
    [
63487385940,
63500432340,
63487407540,
63500453940,
21600,
0,
'BDT'
    ],
    [
63500432340,
63518921940,
63500457540,
63518947140,
25200,
1,
'BDST'
    ],
    [
63518921940,
63531968340,
63518943540,
63531989940,
21600,
0,
'BDT'
    ],
    [
63531968340,
63550457940,
63531993540,
63550483140,
25200,
1,
'BDST'
    ],
    [
63550457940,
63563504340,
63550479540,
63563525940,
21600,
0,
'BDT'
    ],
    [
63563504340,
63581993940,
63563529540,
63582019140,
25200,
1,
'BDST'
    ],
    [
63581993940,
63595126740,
63582015540,
63595148340,
21600,
0,
'BDT'
    ],
    [
63595126740,
63613616340,
63595151940,
63613641540,
25200,
1,
'BDST'
    ],
    [
63613616340,
63626662740,
63613637940,
63626684340,
21600,
0,
'BDT'
    ],
    [
63626662740,
63645152340,
63626687940,
63645177540,
25200,
1,
'BDST'
    ],
    [
63645152340,
63658198740,
63645173940,
63658220340,
21600,
0,
'BDT'
    ],
    [
63658198740,
63676688340,
63658223940,
63676713540,
25200,
1,
'BDST'
    ],
    [
63676688340,
63689734740,
63676709940,
63689756340,
21600,
0,
'BDT'
    ],
    [
63689734740,
63708224340,
63689759940,
63708249540,
25200,
1,
'BDST'
    ],
    [
63708224340,
63721357140,
63708245940,
63721378740,
21600,
0,
'BDT'
    ],
    [
63721357140,
63739846740,
63721382340,
63739871940,
25200,
1,
'BDST'
    ],
    [
63739846740,
63752893140,
63739868340,
63752914740,
21600,
0,
'BDT'
    ],
    [
63752893140,
63771382740,
63752918340,
63771407940,
25200,
1,
'BDST'
    ],
];

sub olson_version { '2010e' }

sub has_dst_changes { 13 }

sub _max_year { 2020 }

sub _new_instance
{
    return shift->_init( @_, spans => $spans );
}

sub _last_offset { 21600 }

my $last_observance = bless( {
  'format' => 'BD%sT',
  'gmtoff' => '6:00',
  'local_start_datetime' => bless( {
    'formatter' => undef,
    'local_rd_days' => 733408,
    'local_rd_secs' => 0,
    'offset_modifier' => 0,
    'rd_nanosecs' => 0,
    'tz' => bless( {
      'name' => 'floating',
      'offset' => 0
    }, 'DateTime::TimeZone::Floating' ),
    'utc_rd_days' => 733408,
    'utc_rd_secs' => 0,
    'utc_year' => 2010
  }, 'DateTime' ),
  'offset_from_std' => 0,
  'offset_from_utc' => 21600,
  'until' => [],
  'utc_start_datetime' => bless( {
    'formatter' => undef,
    'local_rd_days' => 733407,
    'local_rd_secs' => 64800,
    'offset_modifier' => 0,
    'rd_nanosecs' => 0,
    'tz' => bless( {
      'name' => 'floating',
      'offset' => 0
    }, 'DateTime::TimeZone::Floating' ),
    'utc_rd_days' => 733407,
    'utc_rd_secs' => 64800,
    'utc_year' => 2009
  }, 'DateTime' )
}, 'DateTime::TimeZone::OlsonDB::Observance' )
;
sub _last_observance { $last_observance }

my $rules = [
  bless( {
    'at' => '23:59',
    'from' => '2010',
    'in' => 'Oct',
    'letter' => '',
    'name' => 'Dhaka',
    'offset_from_std' => 0,
    'on' => '31',
    'save' => '0',
    'to' => 'max',
    'type' => undef
  }, 'DateTime::TimeZone::OlsonDB::Rule' ),
  bless( {
    'at' => '22:59',
    'from' => '2010',
    'in' => 'Mar',
    'letter' => 'S',
    'name' => 'Dhaka',
    'offset_from_std' => 3600,
    'on' => '31',
    'save' => '1:00',
    'to' => 'max',
    'type' => undef
  }, 'DateTime::TimeZone::OlsonDB::Rule' )
]
;
sub _rules { $rules }


1;

